import type { CollectionConfig } from 'payload'

import { authenticatedReadStaffWrite } from '@/access/staffAccess'

export const PatternReports: CollectionConfig = {
  slug: 'pattern-reports',
  labels: { singular: 'Pattern report', plural: 'Pattern reports' },
  admin: {
    useAsTitle: 'weekStart',
    defaultColumns: ['weekStart', 'recordOrigin', 'updatedAt'],
    description: 'Weekly cross-corpus surfacing generated by small-model jobs.',
  },
  access: authenticatedReadStaffWrite,
  fields: [
    {
      name: 'weekStart',
      type: 'date',
      required: true,
    },
    {
      name: 'patterns',
      type: 'array',
      fields: [
        {
          name: 'kind',
          type: 'select',
          required: true,
          options: [
            { label: 'Visual motif', value: 'visual-motif' },
            { label: 'Conceptual theme', value: 'conceptual-theme' },
            { label: 'Location', value: 'location' },
            { label: 'Material', value: 'material' },
            { label: 'Line momentum', value: 'line-momentum' },
          ],
        },
        {
          name: 'label',
          type: 'text',
          required: true,
        },
        {
          name: 'sampleFieldNoteIDs',
          type: 'array',
          admin: {
            description:
              'Temporary numeric ids for FieldNotes until the collection is registered.',
          },
          fields: [
            {
              name: 'id',
              type: 'number',
              required: true,
            },
          ],
        },
        {
          name: 'sampleArtworks',
          type: 'relationship',
          relationTo: 'artworks',
          hasMany: true,
        },
        {
          name: 'score',
          type: 'number',
        },
      ],
    },
    {
      name: 'digestSummary',
      type: 'textarea',
    },
    {
      name: 'recordOrigin',
      type: 'select',
      required: true,
      defaultValue: 'small-model',
      options: [{ label: 'Small model', value: 'small-model' }],
      admin: { position: 'sidebar' },
    },
  ],
  timestamps: true,
}
