import Link from 'next/link'
import type { CSSProperties } from 'react'

import ArtworkR2Image from '@/components/artwork/ArtworkR2Image'

import VisionAnalysesSection from '@/components/artwork/VisionAnalysesSection'
import VisionComparisonGrid, { type ComparisonItem } from '@/components/artwork/VisionComparisonGrid'
import {
  getArtworkImagePair,
  getPrimaryMediaDimensions,
  resolveSeriesSlug,
} from '@/helpers/artworkCatalog'
import { getSeriesColor } from '@/helpers/seriesColor'
import { formatArtworkYearRange, resolveWallLabelMedium } from '@/lib/artwork/artworkLabels'
import {
  formatEmbeddingModelLabel,
  formatMonthYear,
  resolveEmbeddingMetadataList,
  resolveVisionAnalyses,
  vectorTeasePreview,
  type EmbeddingMetadata,
} from '@/lib/artwork/visionPage'
import type { SimilarArtworkCard } from '@/lib/payload/similarArtworksPage'
import type { Artwork } from '@/payload-types'

import './artwork-page.css'
import './vision-page.css'

const HERO_MAX_WIDTH = 1200
const VECTOR_TEASE_COUNT = 10

function scaleToMaxWidth(
  width: number,
  height: number,
  maxWidth: number,
): { width: number; height: number } {
  if (width <= 0 || height <= 0) {
    return { width: maxWidth, height: Math.round(maxWidth * 0.75) }
  }
  if (width <= maxWidth) return { width, height }
  const scale = maxWidth / width
  return {
    width: maxWidth,
    height: Math.max(1, Math.round(height * scale)),
  }
}

function formatSimilarityScore(similarity: number | undefined): string | null {
  if (typeof similarity !== 'number' || !Number.isFinite(similarity)) return null
  return `${Math.round(similarity * 100)}% similarity`
}

const VISION_PROSE = {
  heading: 'What machines see',
  paragraphs: [
    'This page is a record of how different systems have looked at this work.',
    'The embeddings — rows of numbers generated by models like CLIP and DINOv2 — describe the image mathematically: shapes, colours, spatial relationships, visual texture. They power the similar-works connections above, finding echoes across thirty years of work without any manual tagging. Each model weighs visual features differently. CLIP learned from image-text pairs; DINOv2 learned from images alone. Whether they agree on what\'s similar is itself informative.',
    'The vision analyses are the language layer — what happens when a model is asked to describe what it actually sees. The same prompt, sent to different models, on different dates. Where they converge, something is probably objectively there in the work. Where they diverge, the work is leaving room for interpretation.',
    'Both are dated and model-tagged because they\'re not timeless descriptions. They\'re records of a specific system looking at a specific image at a specific moment. As models improve, the readings get richer. The archive accumulates them all.',
  ],
} as const

export type VisionPageProps = {
  artwork: Artwork
  vectorsByColumn: Record<string, number[]>
  similarWorksByColumn: Record<string, SimilarArtworkCard[]>
}

type SimilarWorkItem = {
  slug: string
  title: string
  imageSrc: string
  imageFallback: string
  similarity?: number
}

function similarWorkItems(works: SimilarArtworkCard[]): SimilarWorkItem[] {
  return works.slice(0, 3).flatMap((work) => {
    const imagePair = getArtworkImagePair(work, 'similar-works')
    if (!imagePair || !work.slug?.trim()) return []
    const item: SimilarWorkItem = {
      slug: work.slug.trim(),
      title: work.title?.trim() || 'Artwork',
      imageSrc: imagePair.src,
      imageFallback: imagePair.fallback,
    }
    if (typeof work.similarity === 'number' && Number.isFinite(work.similarity)) {
      item.similarity = work.similarity
    }
    return [item]
  })
}

function SimilarWorksStrip({ works }: { works: SimilarWorkItem[] }) {
  if (works.length === 0) return null

  return (
    <div className="vision-page__similar">
      <p className="vision-page__similar-label">Via visual similarity:</p>
      <div className="vision-page__similar-grid">
        {works.map((work) => {
          const scoreLabel = formatSimilarityScore(work.similarity)
          return (
            <Link key={work.slug} href={`/${work.slug}`} className="vision-page__similar-link">
              <div className="vision-page__similar-image">
                <ArtworkR2Image
                  src={work.imageSrc}
                  fallbackSrc={work.imageFallback}
                  alt={work.title}
                  className="vision-page__similar-img"
                  loading="lazy"
                  decoding="async"
                />
              </div>
              <div className="vision-page__similar-caption">
                <p className="vision-page__similar-title">{work.title}</p>
                {scoreLabel ? <p className="vision-page__similar-score">{scoreLabel}</p> : null}
              </div>
            </Link>
          )
        })}
      </div>
    </div>
  )
}

function EmbeddingCard({
  metadata,
  vector,
  similarWorks,
  seriesColor,
}: {
  metadata: EmbeddingMetadata
  vector: number[]
  similarWorks: SimilarWorkItem[]
  seriesColor: string
}) {
  const generatedLabel = formatMonthYear(metadata.generatedDate)
  const vectorTease = vectorTeasePreview(vector, VECTOR_TEASE_COUNT)

  return (
    <article
      className="vision-page__embedding-card"
      style={{ '--vision-accent-color': seriesColor } as CSSProperties}
    >
      <div className="vision-page__embedding-header">
        <div>
          <p className="vision-page__embedding-model">
            {formatEmbeddingModelLabel(metadata.model)}
          </p>
          {metadata.shortDescription ? (
            <p className="vision-page__embedding-description">{metadata.shortDescription}</p>
          ) : null}
          {generatedLabel ? (
            <p className="vision-page__embedding-date">Generated: {generatedLabel}</p>
          ) : null}
        </div>
        {metadata.specUrl ? (
          <a
            href={metadata.specUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="vision-page__embedding-spec"
          >
            Model spec →
          </a>
        ) : null}
      </div>

      <div className="vision-page__vector">
        <p className="vision-page__vector-label">The vector · not meant to be read</p>
        <p className="vision-page__vector-tease">{vectorTease}</p>
      </div>

      <SimilarWorksStrip works={similarWorks} />
    </article>
  )
}

function embeddingComparisonItems(
  metadataList: EmbeddingMetadata[],
  vectorsByColumn: Record<string, number[]>,
  similarWorksByColumn: Record<string, SimilarArtworkCard[]>,
  seriesColor: string,
): ComparisonItem[] {
  return metadataList.flatMap((metadata, index) => {
    const vector = vectorsByColumn[metadata.pgVectorColumn]
    if (!vector?.length) return []

    const similarWorks = similarWorkItems(similarWorksByColumn[metadata.pgVectorColumn] ?? [])
    const generatedLabel = formatMonthYear(metadata.generatedDate)

    return [
      {
        id: String(index),
        modelLabel: formatEmbeddingModelLabel(metadata.model),
        dateLabel: generatedLabel,
        preview: metadata.shortDescription ?? `${metadata.dimensions} dimensions`,
        body: (
          <EmbeddingCard
            metadata={metadata}
            vector={vector}
            similarWorks={similarWorks}
            seriesColor={seriesColor}
          />
        ),
      },
    ]
  })
}

function EmbeddingsSection({
  artwork,
  vectorsByColumn,
  similarWorksByColumn,
  seriesColor,
}: {
  artwork: Artwork
  vectorsByColumn: Record<string, number[]>
  similarWorksByColumn: Record<string, SimilarArtworkCard[]>
  seriesColor: string
}) {
  const metadataList = resolveEmbeddingMetadataList(artwork).filter(
    (metadata) => vectorsByColumn[metadata.pgVectorColumn]?.length,
  )

  if (metadataList.length === 0) {
    return (
      <p className="vision-page__null-state">
        Visual embedding data has not yet been generated for this work.
      </p>
    )
  }

  if (metadataList.length === 1) {
    const metadata = metadataList[0]!
    const vector = vectorsByColumn[metadata.pgVectorColumn]!
    const similarWorks = similarWorkItems(similarWorksByColumn[metadata.pgVectorColumn] ?? [])

    return (
      <EmbeddingCard
        metadata={metadata}
        vector={vector}
        similarWorks={similarWorks}
        seriesColor={seriesColor}
      />
    )
  }

  const items = embeddingComparisonItems(
    metadataList,
    vectorsByColumn,
    similarWorksByColumn,
    seriesColor,
  )

  return <VisionComparisonGrid items={items} seriesColor={seriesColor} />
}

export default function VisionPage({
  artwork,
  vectorsByColumn,
  similarWorksByColumn,
}: VisionPageProps) {
  const imagePair = getArtworkImagePair(artwork, 'vision-page')
  const seriesColor = getSeriesColor(resolveSeriesSlug(artwork) ?? 'default')
  const analyses = resolveVisionAnalyses(artwork)
  const sourceDimensions = getPrimaryMediaDimensions(artwork)
  const heroDimensions = imagePair
    ? scaleToMaxWidth(sourceDimensions.width, sourceDimensions.height, HERO_MAX_WIDTH)
    : null

  return (
    <article className="vision-page">
      <div className="vision-page__hero-zone">
        <p className="vision-page__hero-zone-eyebrow">Vision · not the artwork page</p>

        {imagePair && heroDimensions ? (
          <div className="vision-page__hero-image">
            <ArtworkR2Image
              src={imagePair.src}
              fallbackSrc={imagePair.fallback}
              alt={artwork.title ?? 'Artwork'}
              width={heroDimensions.width}
              height={heroDimensions.height}
              className="vision-page__hero-img"
              loading="eager"
              decoding="async"
              fetchPriority="high"
            />
          </div>
        ) : null}

        <div className="vision-page__title-block">
          <h1 className="artwork-image__title">{artwork.title}</h1>
          <h2 className="artwork-image__year">{formatArtworkYearRange(artwork)}</h2>
          <h3 className="artwork-image__medium">{resolveWallLabelMedium(artwork)}</h3>
        </div>
      </div>

      <section id="embeddings" className="vision-page__section">
        <h2 className="vision-page__section-label">Visual Embeddings</h2>
        <EmbeddingsSection
          artwork={artwork}
          vectorsByColumn={vectorsByColumn}
          similarWorksByColumn={similarWorksByColumn}
          seriesColor={seriesColor}
        />
      </section>

      <section id="analyses" className="vision-page__section">
        <h2 className="vision-page__section-label">Vision Analyses</h2>
        <p className="vision-page__section-context">
          Visual descriptions produced by different AI models over time. Same prompt, different
          perspectives.
        </p>
        {analyses.length > 0 ? (
          <VisionAnalysesSection analyses={analyses} seriesColor={seriesColor} />
        ) : (
          <p className="vision-page__null-state">No vision analyses yet for this work.</p>
        )}
      </section>

      <section className="vision-page__section">
        <div className="vision-page__prose-panel">
          <h2 className="vision-page__prose-heading">{VISION_PROSE.heading}</h2>
          {VISION_PROSE.paragraphs.map((paragraph) => (
            <p key={paragraph} className="vision-page__prose-body">
              {paragraph}
            </p>
          ))}
        </div>
      </section>
    </article>
  )
}
