export { artistAsSchemaPerson } from '@/lib/jsonld/artistPerson'
export { buildArtworkJsonLd, generateArtworkJsonLd } from '@/lib/jsonld/artwork'
export type { BuildArtworkJsonLdOptions } from '@/lib/jsonld/artwork'
export { buildEventJsonLd, generateEventJsonLd } from '@/lib/jsonld/event'
export type { BuildEventJsonLdOptions } from '@/lib/jsonld/event'
export { getSiteBaseUrl } from '@/lib/jsonld/site'
