/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artists: Artist;
    'practice-knowledge': PracticeKnowledge;
    series: Series;
    lines: Line;
    'studio-conversations': StudioConversation;
    'pattern-reports': PatternReport;
    episodes: Episode;
    tags: Tag;
    'art-historical-references': ArtHistoricalReference;
    events: Event;
    'image-capture-technologies': ImageCaptureTechnology;
    artworks: Artwork;
    triptychs: Triptych;
    'small-prints': SmallPrint;
    sessions: Session;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    artworks: {
      events: 'events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    'practice-knowledge': PracticeKnowledgeSelect<false> | PracticeKnowledgeSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    lines: LinesSelect<false> | LinesSelect<true>;
    'studio-conversations': StudioConversationsSelect<false> | StudioConversationsSelect<true>;
    'pattern-reports': PatternReportsSelect<false> | PatternReportsSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'art-historical-references': ArtHistoricalReferencesSelect<false> | ArtHistoricalReferencesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'image-capture-technologies': ImageCaptureTechnologiesSelect<false> | ImageCaptureTechnologiesSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    triptychs: TriptychsSelect<false> | TriptychsSelect<true>;
    'small-prints': SmallPrintsSelect<false> | SmallPrintsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'print-set-config': PrintSetConfig;
  };
  globalsSelect: {
    'print-set-config': PrintSetConfigSelect<false> | PrintSetConfigSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'artist')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Single artist identity record (JSON-LD creator). Module A — one row for this site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  /**
   * Name you work under publicly (e.g. Bernard Bolter). Used for the site, JSON-LD, and slug.
   */
  name: string;
  /**
   * Full legal name if different (e.g. Bernard John Bolter IV). Used for credits and formal records; optional.
   */
  nameLegal?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  careerStage?: ('studio' | 'market' | 'institutional') | null;
  /**
   * Hidden on this site — artist, gallery, and collector are separate properties.
   */
  primaryActorType?:
    | ('artist' | 'collector' | 'gallery' | 'artist-collector' | 'artist-gallery' | 'artist-collector-gallery')
    | null;
  actorRoles?: ('artist' | 'collector' | 'gallery')[] | null;
  /**
   * Set automatically when the record is first created.
   */
  platformJoinDate?: string | null;
  externalIdentifiers?:
    | {
        type: 'website' | 'instagram' | 'artnet' | 'artsy' | 'wikidata' | 'ulan' | 'json-ld' | 'google-knowledge-graph';
        value: string;
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Getty ULAN URI, e.g. http://vocab.getty.edu/ulan/500xxxxxx
   */
  ulanUri?: string | null;
  /**
   * Wikidata entity URI, e.g. https://www.wikidata.org/entity/Qxxxxxx
   */
  wikidataUri?: string | null;
  bioFull?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bioMedium?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Single sentence, third person (plain text).
   */
  bioShort?: string | null;
  statementFull?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  statementMedium?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One to two sentences (plain text).
   */
  statementShort?: string | null;
  /**
   * How of making — populated gradually via cataloguing sessions.
   */
  practiceNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Canonical attribution string for listings and loans.
   */
  creditLine?: string | null;
  locations?:
    | {
        city: string;
        country: string;
        type: 'studio' | 'residence' | 'live-work';
        primary?: boolean | null;
        current?: boolean | null;
        /**
         * Year this base was established (optional).
         */
        startYear?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact form destination — never render as raw text on the public site.
   */
  publicEmail?: string | null;
  website?: string | null;
  instagramUrl?: string | null;
  otherLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        institution: string;
        degree?: string | null;
        subject?: string | null;
        yearStart?: number | null;
        yearEnd?: number | null;
        city?: string | null;
        country?: string | null;
        cvVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  selectedCollections?:
    | {
        institutionName: string;
        city?: string | null;
        country?: string | null;
        acquisitionYear?: number | null;
        cvVisible?: boolean | null;
        sourceOfTruth?: ('manual' | 'derived') | null;
        /**
         * Optional link for future derivation workflows.
         */
        linkedArtworkId?: (number | null) | Artwork;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The complete archive of all artworks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  /**
   * Canonical high-res image for image-based works.
   */
  primaryImage?: (number | null) | Media;
  primaryMediaType?: ('image' | 'video' | 'image-and-video') | null;
  /**
   * Alt text for the primary image (accessibility).
   */
  primaryImageAltText?: string | null;
  /**
   * Thumbnail / social / timeline / video poster. Required when primary media type is video.
   */
  posterImage?: (number | null) | Media;
  posterImageAltText?: string | null;
  /**
   * Temporary WordPress image URL until migrated to R2.
   */
  wpImageUrl?: string | null;
  title: string;
  /**
   * Alternate title — also known as (other language or market).
   */
  altTitle?: string | null;
  slug: string;
  /**
   * Primary artist for this work.
   */
  creator: number | Artist;
  series: number | Series;
  /**
   * Auto-set from series.
   */
  seriesSlug?: string | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Set once at creation; immutable. Provenance of the catalogue record.
   */
  recordOrigin: 'artist-catalogued' | 'gallery-catalogued' | 'collector-catalogued' | 'migrated' | 'enrichment-agent';
  /**
   * Four-digit year the work was begun.
   */
  yearCreated: number;
  /**
   * Year finished if different from year created.
   */
  yearCompleted?: number | null;
  /**
   * Mirrors year created — reserved for future slug generation.
   */
  yearStart?: number | null;
  datePublished?: string | null;
  /**
   * Legacy WordPress ID.
   */
  wp_id?: number | null;
  /**
   * Legacy WordPress artwork URL.
   */
  oldWpUrl?: string | null;
  medium:
    | 'acrylic-photo-transfer-on-canvas'
    | 'acrylic-on-canvas'
    | 'mixed-media-on-canvas'
    | 'photo-collage'
    | 'video'
    | 'digital'
    | 'other';
  /**
   * Override or specify when medium is “Other”.
   */
  mediumOther?: string | null;
  /**
   * Gates which dimension sections apply. A work can combine types.
   */
  measurementType: ('physical' | 'digital' | 'time-based')[];
  support?: ('canvas' | 'paper' | 'board' | 'screen' | 'file' | 'other') | null;
  framing?: ('framed' | 'unframed' | 'artist-framed') | null;
  /**
   * Weight in kilograms (physical works).
   */
  weight?: number | null;
  dimensionUnit?: ('cm' | 'in') | null;
  widthWhole?: number | null;
  /**
   * Optional fraction, e.g. 3/16
   */
  widthFraction?: string | null;
  heightWhole?: number | null;
  /**
   * Optional fraction
   */
  heightFraction?: string | null;
  depthWhole?: number | null;
  /**
   * Optional fraction
   */
  depthFraction?: string | null;
  /**
   * Computed on save (Step 7 hook).
   */
  widthMm?: number | null;
  /**
   * Computed on save (Step 7 hook).
   */
  heightMm?: number | null;
  /**
   * Computed on save (Step 7 hook).
   */
  depthMm?: number | null;
  /**
   * Human-readable size string — computed on save (Step 7).
   */
  dimensionsDisplay?: string | null;
  /**
   * widthMm ÷ heightMm (physical) or widthPx ÷ heightPx (digital-only).
   */
  aspectRatio?: number | null;
  widthPx?: number | null;
  heightPx?: number | null;
  resolutionDpi?: number | null;
  /**
   * Native working file format (TIFF, PSD, MP4, …).
   */
  fileFormat?: string | null;
  /**
   * File size in MB.
   */
  fileSize?: number | null;
  colorSpace?: ('sRGB' | 'Adobe RGB' | 'P3' | 'CMYK' | 'other') | null;
  /**
   * e.g. HH:MM:SS or prose for open-ended works.
   */
  duration?: string | null;
  /**
   * Computed from duration (Step 7).
   */
  durationSeconds?: number | null;
  looped?: boolean | null;
  soundDesign?: ('sound' | 'silent' | 'ambient' | 'variable') | null;
  condition?: ('excellent' | 'good' | 'fair' | 'poor') | null;
  conditionNotes?: string | null;
  workState?: ('original' | 'reworked' | 'restored' | 'damaged' | 'lost') | null;
  workStateNotes?: string | null;
  /**
   * Date this work state was recorded.
   */
  workStateDate?: string | null;
  /**
   * Why these materials and process choices matter.
   */
  materialAndProcessMeaning?: string | null;
  /**
   * Timestamped change records: [{ date, description, type: restoration|rework|damage|relining|other }]
   */
  stateVersions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Layout tier on the public site. Rule-of-thumb: longest side <300mm → sm; 300–800 → md; 800–2000 → lg; >2000 → xl.
   */
  sizeTier?: ('sm' | 'md' | 'lg' | 'xl') | null;
  orientation?: ('portrait' | 'landscape' | 'square') | null;
  /**
   * City where the work was made (controlled vocabulary).
   */
  city?: string | null;
  /**
   * Country (controlled vocabulary).
   */
  country?: string | null;
  /**
   * Getty TGN URI for the city (JSON-LD / agent).
   */
  cityTgnUri?: string | null;
  movementTags?: (number | Tag)[] | null;
  styleTags?: (number | Tag)[] | null;
  subjectTags?: (number | Tag)[] | null;
  genreTags?: (number | Tag)[] | null;
  periodTags?: (number | Tag)[] | null;
  /**
   * Abstract terms (memory, erasure, mediation, …).
   */
  conceptualKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Step 10 — reverse of **Event → Artworks**. Edit memberships only on the event document.
   */
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  artHistoricalReferences?: (number | ArtHistoricalReference)[] | null;
  /**
   * Prose on art-historical connections (agent draft, artist confirms).
   */
  artHistoricalContext?: string | null;
  /**
   * Where this work sits in the practice arc.
   */
  seriesContext?: string | null;
  /**
   * What this work pushes against (intent layer).
   */
  consciousRejections?: string | null;
  /**
   * What this work does that has not been done before.
   */
  formalContributionAssessment?: string | null;
  /**
   * 1–3 sentences; meta, hover cards, schema.org (EN/DE via locale).
   */
  descriptionShort?: string | null;
  /**
   * Extended catalogue entry (EN/DE via locale).
   */
  descriptionLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Legacy body — prefer descriptionLong; kept for unmigrated rows.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Artist: what the work means and does (first person). Never AI-generated.
   */
  intent?: string | null;
  /**
   * Intended vs actual outcome; productive failure.
   */
  intentVsOutcome?: string | null;
  /**
   * Experiential account of making (first person).
   */
  makingNote?: string | null;
  /**
   * Immediate seed (image, detail, memory) — not full art-historical context.
   */
  directInspiration?: string | null;
  /**
   * Standing in front of the work: scale, surface, light.
   */
  encounterNote?: string | null;
  /**
   * Where this sits in the practice flow vs neighbouring works.
   */
  workContext?: string | null;
  /**
   * Factual technique / departures from series norms (dialogue + inference).
   */
  processNotes?: string | null;
  /**
   * Photographic or archival sources incorporated; blank if none.
   */
  sourceMaterials?: string | null;
  /**
   * Agent visual draft — starting point for artist-edited public text.
   */
  aiDescription?: string | null;
  /**
   * Semantic/mood seed — can inform encounterNote and embeddings pipeline.
   */
  aiVibe?: string | null;
  /**
   * Agent-suggested hex values; artist may correct.
   */
  dominantColors?:
    | {
        hex: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Acrylic field areas vs transfer — when medium includes paint.
   */
  paintedFieldColors?:
    | {
        hex: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Agent: composition, visual weight, dominant direction.
   */
  compositionalNotes?: string | null;
  /**
   * Pipeline version, e.g. model + CLIP checkpoint.
   */
  analysisModelVersion?: string | null;
  /**
   * Artist-layer visibility history: [{ date, event, context, effect }]. JSON per Addendum F.
   */
  recognitionTimeline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * CLIP embedding stored as vector(1536); use SQL/API for similarity, not this cell.
   */
  clipEmbedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Legacy JSON embedding placeholder — migrate to clipEmbedding / drop after cutover.
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Deprecated free-text genre — prefer Classification → genreTags.
   */
  genre?: string | null;
  /**
   * Other photographs that are part of understanding the work — different angles (e.g. sculpture sides), verso, raking light, scale in hand. Not studio/process documentation (use Documentation photos).
   */
  alternateViewImages?:
    | {
        image: number | Media;
        caption?: string | null;
        altText?: string | null;
        /**
         * Width ÷ height for layout.
         */
        aspectRatio?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Close-ups — texture, passage, signature, material surface.
   */
  detailImages?:
    | {
        image: number | Media;
        caption?: string | null;
        altText?: string | null;
        aspectRatio?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Work shown installed in a space (venue and date optional).
   */
  installationShots?:
    | {
        image: number | Media;
        venue?: string | null;
        date?: string | null;
        altText?: string | null;
        aspectRatio?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Photographs that document the work’s making or context — not other angles of the finished piece (use Alternate views) and not gallery installation (use Installation shots).
   */
  documentationImages?:
    | {
        image: number | Media;
        caption?: string | null;
        altText?: string | null;
        aspectRatio?: number | null;
        documentationRole?: ('studio' | 'process' | 'condition' | 'publication' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AR target (e.g. Mediums of Perception / mind.js). Series-specific.
   */
  arTargetImage?: (number | null) | Media;
  /**
   * Primary video file (MP4, MOV, WebM). Wins over videoUrl if both set.
   */
  videoFile?: (number | null) | Media;
  /**
   * Primary embeddable URL (YouTube, Vimeo, …). Cleared when videoFile is set.
   */
  videoUrl?: string | null;
  videoCaption?: string | null;
  /**
   * Documentation of a physical work (walkthrough, process film) — URL.
   */
  documentationVideoUrl?: string | null;
  /**
   * Documentation video upload. Wins over documentationVideoUrl if both set.
   */
  documentationVideoFile?: (number | null) | Media;
  /**
   * Additional clips (making-of, interviews, etc.). Use videoRole primary/documentation for JSON-LD mapping.
   */
  videos?:
    | {
        videoType: 'upload' | 'youtube' | 'vimeo' | 'url';
        videoFile?: (number | null) | Media;
        videoUrl?: string | null;
        posterImage?: (number | null) | Media;
        title?: string | null;
        description?: string | null;
        videoRole?: ('primary' | 'documentation' | 'makingOf' | 'ar' | 'interview' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Deprecated — migrate to alternateViewImages / detailImages / installationShots.
   */
  additionalImages?:
    | {
        image: number | Media;
        caption?: string | null;
        imageRole?: ('detail' | 'installation' | 'process' | 'reverse' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  arEnabled?: boolean | null;
  /**
   * Metres; defaults from width mm ÷ 1000 on save.
   */
  arWidthM?: number | null;
  /**
   * Metres; defaults from height mm ÷ 1000 on save.
   */
  arHeightM?: number | null;
  /**
   * Depth in metres (framed works).
   */
  arDepthM?: number | null;
  /**
   * Generated .usdz URL (R2).
   */
  arModelUrl?: string | null;
  /**
   * Generated .glb URL for Android.
   */
  arModelGlbUrl?: string | null;
  arAllowScaling?: boolean | null;
  arLastGenerated?: string | null;
  locationCreated?: {
    /**
     * e.g. studio in CANK, Neukölln
     */
    label?: string | null;
    city?: string | null;
    country?: string | null;
    countryCode?: string | null;
    lat?: number | null;
    lng?: number | null;
  };
  artworkHolder?: {
    holderType?: ('Person' | 'Organization') | null;
    /**
     * Display name for the current holder (private).
     */
    holderName?: string | null;
    holderUrl?: string | null;
  };
  provenanceNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  currentLocation?: {
    category?: ('artists-studio' | 'private-collection' | 'institution' | 'on-loan') | null;
    /**
     * Address or holder detail (private).
     */
    locationDetail?: string | null;
  };
  /**
   * JSON array: { transactionId, ownerPrivate, displayName, city, dateAcquired, dateRelinquished, claimStatus, collectorVisible, notes }. Link sales via transactionId.
   */
  ownershipHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Uncheck when the studio-to-first-owner chain is not traceable.
   */
  provenanceOriginKnown?: boolean | null;
  /**
   * JSON array: { institution, dateOut, dateReturned, eventId (numeric id → events), notes }.
   */
  loanHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * JSON array: { claim, evidenceBasis, confidenceLevel: documented-fact | credible-inference | institutional-assertion | speculation }.
   */
  provenanceConfidenceLayer?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional manual cross-links; prefer assigning works on the Event document.
   */
  exhibitionHistory?:
    | {
        event: number | Event;
        workIncluded?: boolean | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  availabilityStatus?: ('available' | 'sold' | 'not-for-sale' | 'on-loan' | 'reserved' | 'on-consignment') | null;
  /**
   * Gallery and dates when on consignment.
   */
  consignmentDetails?: string | null;
  listingCurrency?: ('EUR' | 'USD' | 'GBP' | 'CHF' | 'other') | null;
  /**
   * In listingCurrency.
   */
  askingPrice?: number | null;
  originalAskingPrice?: number | null;
  priceNotes?: string | null;
  insuranceValue?: number | null;
  insuranceValueDate?: string | null;
  /**
   * Gallery inventory / stock id (private).
   */
  galleryReference?: string | null;
  /**
   * Wall text / press release for this work (when applicable).
   */
  galleryText?: string | null;
  /**
   * JSON array of sales: transactionId (UUID), saleDate, salePrice, saleCurrency, exchangeRateToEur, buyerPrivate, buyerCity, channel, galleryName, auctionHouse, invoiceReference, commissionRate, netToArtist, vatApplicable, vatRate, editionNumber, notes.
   */
  salesRecord?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Σ netToArtist × exchangeRateToEur — computed on save.
   */
  totalRevenue?: number | null;
  editionType?: ('unique' | 'limited-edition' | 'open-edition' | 'artist-proof-only') | null;
  editions?:
    | {
        formatLabel: string;
        widthCm?: number | null;
        heightCm?: number | null;
        substrate?: string | null;
        printTechnique?: ('giclee' | 'screenprint' | 'lithograph' | 'etching' | 'other') | null;
        totalEditionSize?: number | null;
        artistProofs?: number | null;
        remaining?: number | null;
        pricePerPrint?: number | null;
        currency?: ('EUR' | 'USD' | 'GBP') | null;
        certificate?: boolean | null;
        signature?: ('signed' | 'unsigned' | 'signed-on-request') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Public-facing notes on the edition programme.
   */
  editionNotes?: string | null;
  /**
   * Legacy — use availabilityStatus.
   */
  isForSale?: boolean | null;
  offers?: {
    price?: number | null;
    priceCurrency?: ('EUR' | 'USD' | 'GBP') | null;
    availability?: ('https://schema.org/InStock' | 'https://schema.org/SoldOut' | 'https://schema.org/PreOrder') | null;
    inquiryUrl?: string | null;
  };
  /**
   * Legacy — migrate rows into editions[].
   */
  printEditions?:
    | {
        editionSize?: number | null;
        /**
         * e.g. A3, 50x70cm
         */
        format?: string | null;
        /**
         * e.g. matte paper, dibond
         */
        substrate?: string | null;
        price?: number | null;
        priceCurrency?: ('EUR' | 'USD' | 'GBP') | null;
        availability?: ('https://schema.org/InStock' | 'https://schema.org/SoldOut') | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Labeled external links for SEO. For schema.org URI list see Schema.org tab.
   */
  sameAs?:
    | {
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Maps to rightsstatement.org / CC URIs in JSON-LD output.
   */
  license?: ('all-rights-reserved' | 'cc-by' | 'cc-by-nc' | 'cc-by-nc-nd' | 'cc-by-sa') | null;
  /**
   * Attribution line, e.g. Bernard Bolter, Title, 2021. Courtesy the artist.
   */
  creditText?: string | null;
  /**
   * Wikidata, institution, catalogue URLs for schema.org sameAs array.
   */
  sameAsUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Last generated VisualArtwork JSON-LD (Step 13).
   */
  jsonldPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Stub: QuantitativeValue width — optional sub-preview for debugging.
   */
  jsonldWidthPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Stub: QuantitativeValue height.
   */
  jsonldHeightPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Stub: schema.org Person + identifier[] (ULAN, Wikidata).
   */
  jsonldCreatorPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Source photograph: technology, origin, historical context.
   */
  mop_sourcePhotographDetails?: string | null;
  mop_imageCaptureType?: ('daguerreotype' | 'ambrotype' | 'lithograph' | 'aerial' | 'satellite' | 'digital') | null;
  /**
   * Historical context (EN/DE via locale).
   */
  mop_historicalContext?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mop_triptychPosition?: ('panel-1' | 'panel-2' | 'panel-3' | 'standalone') | null;
  /**
   * Triptych grouping label or id (replace with relation → TriptychGroups when that collection exists).
   */
  mop_triptychGroupNote?: string | null;
  /**
   * AR video layer (mind.js).
   */
  mop_arVideoUrl?: string | null;
  /**
   * Rap script for AR audio layer.
   */
  mop_arRapScript?: string | null;
  /**
   * Map pin (series-specific).
   */
  mop_lat?: number | null;
  mop_lng?: number | null;
  /**
   * A Colorful History series-specific data. Sub-groups map to spec Groups 1–7.
   */
  ach?: {
    mapAndTour?: {
      /**
       * Whether this artwork appears on the ACH map. Default false; false for all MoW works.
       */
      mapPresence?: boolean | null;
      /**
       * GPS latitude. Null if mapPresence is false.
       */
      lat?: number | null;
      /**
       * GPS longitude. Null if mapPresence is false.
       */
      lng?: number | null;
      /**
       * Computed from base city field via the Group 1 mapping. Never manually edited.
       */
      cityPlaceholderColor?: string | null;
      /**
       * Position in the series tour for this artwork city. Set only when a tour is active.
       */
      tourSequence?: number | null;
      /**
       * Include in the Grand Tour sequence.
       */
      grandTour?: boolean | null;
      /**
       * Position in the Grand Tour. Set only when grandTour is true.
       */
      grandTourSequence?: number | null;
      /**
       * What Bernard says when this stop is active in a tour. 2–4 sentences, first person. Never drafted by the agent.
       */
      tourStopCopy?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    overlay?: {
      /**
       * Exactly 3 colours extracted from painted fields. Ordered: used for overlay rects (rotating) and AR buttons (fixed positions).
       */
      overlayColors?:
        | {
            hex: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Maximum 4 rectangles, positioned as percentage strings. Resolution-independent — never pixels or floats.
       */
      overlayRects?:
        | {
            color: string;
            /**
             * Percent string e.g. "8%".
             */
            x: string;
            /**
             * Percent string.
             */
            y: string;
            /**
             * Percent string.
             */
            w: string;
            /**
             * Percent string.
             */
            h: string;
            id?: string | null;
          }[]
        | null;
    };
    sourcePhotograph?: {
      /**
       * The historical photograph Bernard transferred to canvas.
       */
      sourceImage?: (number | null) | Media;
      /**
       * Alt text for the source photograph.
       */
      sourceImageAltText?: string | null;
      /**
       * Title as known in the archive or catalogue.
       */
      sourceTitle?: string | null;
      /**
       * Photographer or institution if individual creator unknown.
       */
      sourceCreator?: string | null;
      /**
       * Wikidata entity for the photographer or institution.
       */
      sourceCreatorWikidataUri?: string | null;
      /**
       * Human-readable date. e.g. c. 1861 or 1895–1900.
       */
      approximateDate?: string | null;
      /**
       * Earliest 4-digit year parsed from approximateDate.
       */
      approximateDateYear?: number | null;
      /**
       * The technology used to make this source photograph. Agent proposes from date and image; Bernard confirms.
       */
      imageCaptureType?: (number | null) | ImageCaptureTechnology;
      /**
       * Wikidata entity for this specific photograph, if one exists.
       */
      sourceWikidataUri?: string | null;
      /**
       * Full Wikimedia Commons file-page URL.
       */
      sourceWikimediaCommonsUrl?: string | null;
      /**
       * Archive, museum, or library holding the original.
       */
      sourceInstitution?: string | null;
      /**
       * Wikidata entity for the holding institution.
       */
      sourceInstitutionWikidataUri?: string | null;
      /**
       * Direct URL to the institution catalogue record, if one exists.
       */
      sourceInstitutionUrl?: string | null;
      /**
       * License under which the source photograph is used.
       */
      sourceLicense?: ('cc0' | 'cc-by' | 'cc-by-sa' | 'public-domain' | 'other') | null;
      /**
       * URL to the specific license.
       */
      sourceLicenseUrl?: string | null;
      /**
       * Assembled from creator, title, date, institution, license. Auto-generated.
       */
      sourceCredit?: string | null;
    };
    location?: {
      /**
       * Wikidata entity for the specific landmark depicted (not just the city).
       */
      locationWikidataUri?: string | null;
      /**
       * Getty Thesaurus of Geographic Names URI. Used in JSON-LD alongside Wikidata.
       */
      locationTGNUri?: string | null;
      /**
       * Wikipedia article for the depicted location. Localized — EN/DE editions.
       */
      wikipediaUrl?: string | null;
      /**
       * Passage Bernard selects as relevant — not the article introduction. Agent presents candidates; Bernard selects.
       */
      wikipediaExcerpt?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Editorial selection — not comprehensive history. Drawn out in dialogue, never drafted by agent.
       */
      keyHistoricalDates?:
        | {
            year: number;
            /**
             * Short description of the event for that year.
             */
            event: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Bernard contextual text. For standalone works: what drove this painting. For MoP panels: image-capture context. Never drafted by agent.
       */
      conceptCopy?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Ambient audio for the location. UI deferred post-June. Optional.
       */
      fieldRecordingUrl?: (number | null) | Media;
      /**
       * Attribution if the recording is not Bernard's own.
       */
      fieldRecordingCredit?: string | null;
    };
    revealSlider?: {
      /**
       * Canvas after photo transfer, before painted fields. Must match the crop and framing of primaryImage exactly.
       */
      transferImage?: (number | null) | Media;
      /**
       * Direction of the reveal slider. Bernard chooses per painting based on painted field positions.
       */
      sliderAxis?: ('horizontal' | 'vertical') | null;
    };
    /**
     * Mind.js image-target AR experience. Schema-only at launch — Art/Official does not prompt for these fields yet.
     */
    ar?: {
      /**
       * Activates the AR section. Only true once at least one video and the marker file are ready.
       */
      arEnabled?: boolean | null;
      /**
       * Compiled .mind binary for mind-ar-js. Generate at hiukim.github.io/mind-ar-js-doc/tools/compile from primaryImage.
       */
      arMarkerFile?: (number | null) | Media;
      /**
       * Set by Art/Official after successful marker upload.
       */
      arMarkerStatus?: ('pending' | 'generated' | 'failed') | null;
      /**
       * One colour per AR button: index 0 → Making, 1 → History, 2 → Freestyle. Pre-filled from overlayColors; Bernard may reorder.
       */
      arButtonColors?:
        | {
            hex: string;
            id?: string | null;
          }[]
        | null;
      /**
       * One entry per type: making, history, freestyle.
       */
      arVideos?:
        | {
            type: 'making' | 'history' | 'freestyle';
            videoUrl: number | Media;
            posterImage?: (number | null) | Media;
            /**
             * Duration in seconds.
             */
            duration?: number | null;
            /**
             * VTT caption file.
             */
            captions?: (number | null) | Media;
            id?: string | null;
          }[]
        | null;
      /**
       * Full transcript of the History video. Never AI-generated from inference — Bernard provides or Art/Official transcribes from audio.
       */
      historyTranscript?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      /**
       * Full transcript of the Freestyle rap video.
       */
      freestyleTranscript?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    /**
     * Visible only when the artwork is in the Mediums of Perception or Mediums of War series.
     */
    mop?: {
      /**
       * Confirmed from Group 3 work — typically the same value as ach.sourcePhotograph.imageCaptureType.
       */
      imageCaptureType?: (number | null) | ImageCaptureTechnology;
      /**
       * Display label as it appears on the artwork page. e.g. "Daguerreotype, c. 1861".
       */
      imageCaptureLabel?: string | null;
      /**
       * Panel position in the triptych.
       */
      triptychPosition?: ('I' | 'II' | 'III') | null;
      /**
       * ACH page commerce status. Distinct from base archive availabilityStatus.
       */
      availabilityStatus?: ('original-available' | 'sold' | 'prints-only') | null;
      /**
       * Editorial links to other triptychs in the MoP series. Optional.
       */
      relatedTriptychs?: (number | Triptych)[] | null;
    };
  };
  dcs_photoTitle?: string | null;
  dcs_cityData?: {
    population?: number | null;
    /**
     * km²
     */
    area?: number | null;
    /**
     * per km²
     */
    density?: number | null;
    /**
     * metres
     */
    elevation?: number | null;
  };
  dcs_videos?:
    | {
        videoType: 'upload' | 'youtube' | 'vimeo' | 'url';
        videoFile?: (number | null) | Media;
        videoUrl?: string | null;
        posterImage?: (number | null) | Media;
        title?: string | null;
        videoRole?: ('makingOf' | 'documentation' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  mc_cityData?: {
    population?: number | null;
    /**
     * km²
     */
    area?: number | null;
    /**
     * per km²
     */
    density?: number | null;
    /**
     * metres
     */
    elevation?: number | null;
  };
  mc_videos?:
    | {
        videoType: 'upload' | 'youtube' | 'vimeo' | 'url';
        videoFile?: (number | null) | Media;
        videoUrl?: string | null;
        posterImage?: (number | null) | Media;
        title?: string | null;
        videoRole?: ('makingOf' | 'documentation' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Practice series definitions used by artworks and public series pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  yearStart?: number | null;
  /**
   * Leave empty when the series is ongoing.
   */
  yearEnd?: number | null;
  city?: string | null;
  country?: string | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  /**
   * Computed JSON-LD snapshot for series pages.
   */
  jsonldOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Controlled vocabulary tags for artworks and events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  type: 'movement' | 'style' | 'subject' | 'genre' | 'period';
  /**
   * Optional Getty AAT URI.
   */
  aatUri?: string | null;
  /**
   * Optional Iconclass notation.
   */
  iconclassNotation?: string | null;
  /**
   * Optional Library of Congress Subject Heading URI.
   */
  lcshUri?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All professional events in the artist CV and exhibition history.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  /**
   * Stable UUID for integrations.
   */
  eventId?: string | null;
  eventType:
    | 'solo-exhibition'
    | 'group-exhibition'
    | 'art-fair'
    | 'residency'
    | 'award'
    | 'publication'
    | 'bibliography'
    | 'public-commission'
    | 'talk-panel'
    | 'screening'
    | 'performance'
    | 'education'
    | 'other';
  eventTypeCustom?: string | null;
  status: 'draft' | 'published';
  featured?: boolean | null;
  startDate: string;
  endDate?: string | null;
  isOngoing?: boolean | null;
  openingDate?: string | null;
  /**
   * Computed from startDate.
   */
  yearStart?: number | null;
  venueName?: string | null;
  venueCity?: string | null;
  venueCountry?: string | null;
  venueTgnUri?: string | null;
  venueUrl?: string | null;
  venueWikidataUri?: string | null;
  isOnline?: boolean | null;
  onlineEventUrl?: string | null;
  additionalVenues?:
    | {
        venueName?: string | null;
        venueCity?: string | null;
        venueCountry?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        venueUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Authority field for artwork ↔ event. Appears on Artwork → Classification → Events as a read-only join.
   */
  artworks?: (number | Artwork)[] | null;
  /**
   * How this work was presented in this event (optional).
   */
  artworkPresentationNote?: string | null;
  organiser?: string | null;
  curator?: string | null;
  role?:
    | (
        | 'solo'
        | 'group'
        | 'duo'
        | 'invited-artist'
        | 'artist-in-residence'
        | 'awardee'
        | 'speaker'
        | 'panellist'
        | 'screened-artist'
        | 'commissioned-artist'
      )
    | null;
  coExhibitors?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  catalogue?: boolean | null;
  catalogueUrl?: string | null;
  pressUrl?: string | null;
  recordingUrl?: string | null;
  descriptionShort?: string | null;
  descriptionLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  artistNote?: string | null;
  pressQuote?: string | null;
  publicationTitle?: string | null;
  publicationAuthor?: string | null;
  bibliographyAuthor?: string | null;
  publicationIssn?: string | null;
  publicationIsbn?: string | null;
  publicationPages?: string | null;
  publicationUrl?: string | null;
  awardGrantingOrganisation?: string | null;
  awardAmount?: number | null;
  awardAmountCurrency?: ('EUR' | 'USD' | 'GBP' | 'CHF' | 'other') | null;
  awardOutcome?: ('winner' | 'shortlisted' | 'nominated' | 'honourable-mention') | null;
  residencyOrganisation?: string | null;
  residencyType?: ('studio' | 'live-work' | 'research' | 'production' | 'international') | null;
  residencyWorksProduced?: string | null;
  institution?: string | null;
  degree?: string | null;
  subject?: string | null;
  /**
   * Include on public CV.
   */
  cvVisible?: boolean | null;
  commissionClient?: string | null;
  commissionSite?: string | null;
  commissionBudget?: number | null;
  cvSection?:
    | (
        | 'education'
        | 'solo-exhibitions'
        | 'group-exhibitions'
        | 'art-fairs'
        | 'awards-prizes'
        | 'residencies'
        | 'public-commissions'
        | 'publications'
        | 'bibliography'
        | 'talks-panels'
        | 'screenings'
        | 'performances'
        | 'other'
      )
    | null;
  cvDisplayTitle?: string | null;
  cvPriority?: number | null;
  excludeFromCv?: boolean | null;
  jsonldSameAs?:
    | {
        uri?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Computed event JSON-LD preview.
   */
  jsonldPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Referenced artworks and artists in dialogue with Bernard's practice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "art-historical-references".
 */
export interface ArtHistoricalReference {
  id: number;
  artworkTitle: string;
  artistName: string;
  yearCreated?: number | null;
  medium?: string | null;
  institution?: string | null;
  /**
   * Reference-only image URL (not publicly rendered).
   */
  imageUrl?: string | null;
  /**
   * Authoritative source URL (museum record, Wikidata, etc.).
   */
  referenceUrl?: string | null;
  /**
   * Optional Wikidata URI for the referenced work.
   */
  wikidataUri?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photographic and image-making technologies referenced by ACH source photographs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-capture-technologies".
 */
export interface ImageCaptureTechnology {
  id: number;
  /**
   * Display name. e.g. Daguerreotype, Wet plate collodion.
   */
  name: string;
  /**
   * Auto-generated from name on create; immutable thereafter.
   */
  slug?: string | null;
  /**
   * What this technology is, how it works, what distinguishes its visual qualities.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Four-digit year this technology came into widespread use.
   */
  approximatePeriodStart?: number | null;
  /**
   * Four-digit year it fell out of common use. Leave null if still active.
   */
  approximatePeriodEnd?: number | null;
  /**
   * Representative example illustrating the technology's visual character.
   */
  exampleImage?: (number | null) | Media;
  /**
   * Attribution string for the example image.
   */
  exampleImageCredit?: string | null;
  /**
   * Wikidata entity URI. e.g. https://www.wikidata.org/entity/Q178227 (Daguerreotype).
   */
  wikidataUri?: string | null;
  /**
   * Wikipedia article URL. Localized — EN and DE link to their respective language editions.
   */
  wikipediaUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * MoP triptych sets — three panels sold and catalogued as a unit. Commerce fields live here, not on individual artworks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "triptychs".
 */
export interface Triptych {
  id: number;
  title: string;
  slug: string;
  /**
   * Usually Mediums of Perception or Mediums of War.
   */
  series: number | Series;
  status: 'draft' | 'published' | 'archived';
  /**
   * Four-digit year the triptych was begun.
   */
  yearStart?: number | null;
  /**
   * Year finished if different from year start.
   */
  yearCompleted?: number | null;
  /**
   * Primary city context for this triptych.
   */
  city?: string | null;
  country?: string | null;
  /**
   * Exactly three panels. Panel I = earliest technology, II = historical print, III = contemporary.
   */
  panels: {
    artwork: number | Artwork;
    position: 'I' | 'II' | 'III';
    id?: string | null;
  }[];
  /**
   * Overview of this triptych as a single work.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 1–3 sentences for cards and meta.
   */
  descriptionShort?: string | null;
  descriptionLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What this triptych means as a whole — first person. Never AI-generated.
   */
  intent?: string | null;
  conceptualKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  artHistoricalReferences?: (number | ArtHistoricalReference)[] | null;
  artHistoricalContext?: string | null;
  /**
   * Where this triptych sits in the MoP arc.
   */
  seriesContext?: string | null;
  /**
   * What this triptych does that has not been done before — confirmed by Bernard.
   */
  formalContributionAssessment?: string | null;
  /**
   * Vendure product ID for the original triptych set.
   */
  vendureProductId?: string | null;
  printSets?:
    | {
        size: 'large' | 'small';
        /**
         * Total edition size (e.g. 15 large, 30 small). Never changes.
         */
        edition: number;
        /**
         * Vendure product ID for this print size.
         */
        vendureProductId: string;
        /**
         * Remaining prints — synced from Vendure via webhook only. Initialised from edition on first save.
         */
        printAvailableCount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Date the print edition went on sale.
   */
  printEditionReleaseDate?: string | null;
  /**
   * Hand-signed and numbered by Bernard.
   */
  signedAndNumbered?: boolean | null;
  /**
   * Provenance — staff only, never in public API.
   */
  originalsSoldDate?: string | null;
  /**
   * Buyer name or institution — staff only.
   */
  originalsBuyer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents that brief the Art/Official agent at session start.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-knowledge".
 */
export interface PracticeKnowledge {
  id: number;
  /**
   * One of: biography, artist-statement, series, visual-vocabulary, art-historical-touchstones, preferred-vocabulary
   */
  slug: string;
  /**
   * Heading used when assembling the system prompt.
   */
  sectionLabel: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'active' | 'draft';
  /**
   * Lower numbers appear first in the prompt.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Active investigations that connect FieldNotes, Episodes, Artworks, and conversations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lines".
 */
export interface Line {
  id: number;
  name: string;
  description?: string | null;
  status: 'active' | 'dormant' | 'closed';
  /**
   * Who introduced this line (manual or model suggestion).
   */
  recordOrigin: 'user' | 'small-model';
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form thinking captured through small-model conversation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-conversations".
 */
export interface StudioConversation {
  id: number;
  messages: {
    role: 'user' | 'assistant';
    content: string;
    timestamp: string;
    id?: string | null;
  }[];
  summary?: string | null;
  /**
   * JSON number array until pgvector columns are introduced.
   */
  summaryEmbedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lines?: (number | Line)[] | null;
  relatedArtwork?: (number | null) | Artwork;
  relatedEpisode?: (number | null) | Episode;
  recordOrigin: 'user';
  updatedAt: string;
  createdAt: string;
}
/**
 * MoP episode records with storyboard and clip assembly notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: number;
  title: string;
  series: 'outsider-art-review' | 'rap-critic' | 'studio-fails' | 'studio-series';
  status: 'concept' | 'storyboard' | 'shot' | 'uploaded' | 'edited' | 'posted';
  concept?: string | null;
  shotList?: string | null;
  storyboard?:
    | {
        name: string;
        mediaType?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  assembly?:
    | {
        beatName?: string | null;
        /**
         * Temporary FieldNote id linkage until field-notes collection is registered.
         */
        clipFieldNoteId?: number | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  captionDrafts?:
    | {
        text: string;
        channel?: string | null;
        id?: string | null;
      }[]
    | null;
  lines?: (number | Line)[] | null;
  /**
   * Temporary join substitute until field-notes collection is registered.
   */
  clipFieldNoteIds?:
    | {
        id: number;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Weekly cross-corpus surfacing generated by small-model jobs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pattern-reports".
 */
export interface PatternReport {
  id: number;
  weekStart: string;
  patterns?:
    | {
        kind: 'visual-motif' | 'conceptual-theme' | 'location' | 'material' | 'line-momentum';
        label: string;
        /**
         * Temporary numeric ids for FieldNotes until the collection is registered.
         */
        sampleFieldNoteIDs?:
          | {
              id: number;
            }[]
          | null;
        sampleArtworks?: (number | Artwork)[] | null;
        score?: number | null;
        id?: string | null;
      }[]
    | null;
  digestSummary?: string | null;
  recordOrigin: 'small-model';
  updatedAt: string;
  createdAt: string;
}
/**
 * Curated square paintings available in the print set builder. Vendure product ID is on Print set config global — not per row.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "small-prints".
 */
export interface SmallPrint {
  id: number;
  /**
   * Source painting — must have orientation “square”. Title, city, series, and primaryImage come from this relation.
   */
  artwork: number | Artwork;
  /**
   * Whether this print is selectable in the set builder.
   */
  available?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Art/Official session transcripts (not exposed to anonymous API).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  sessionId?: string | null;
  sessionType: 'artwork-cataloguing' | 'triptych-cataloguing' | 'artist-statement' | 'biography' | 'onboarding';
  status: 'in-progress' | 'completed' | 'abandoned';
  artistId?: (number | null) | Artist;
  artworkRecord?: (number | null) | Artwork;
  /**
   * Optional — link when refining an existing triptych corpus.
   */
  triptychRecord?: (number | null) | Triptych;
  completedAt?: string | null;
  /**
   * Full Anthropic message array (opaque).
   */
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current pre-upload question (1–4). Updated by Art/Official as the dialogue advances.
   */
  preUploadStep?: number | null;
  firstImpression?: string | null;
  secondDescription?: string | null;
  /**
   * Art/Official: slot id highlighted in the Media uploads panel (set by the agent).
   */
  highlightedMediaSlot?: string | null;
  /**
   * Art/Official staged media attachments (images, videos, URLs) before commit.
   */
  stagedMedia?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of { field, value, confidence, source, timestamp }.
   */
  fieldUpdateTimeline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  agentDraftDescriptionShort?: string | null;
  agentDraftDescriptionLong?: string | null;
  agentDraftConceptualKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  agentDraftFormalContributionAssessment?: string | null;
  sessionNotes?: string | null;
  weakPhases?: ('pre-upload' | 'identity' | 'intent' | 'art-historical' | 'classification' | 'confirmation')[] | null;
  blindDescriptionUseful?: boolean | null;
  formalContributionAccuracy?: ('accurate' | 'partial' | 'missed') | null;
  /**
   * Flag for follow-up refinement pass.
   */
  dialogueRefinementFlag?: boolean | null;
  refinementNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'practice-knowledge';
        value: number | PracticeKnowledge;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'lines';
        value: number | Line;
      } | null)
    | ({
        relationTo: 'studio-conversations';
        value: number | StudioConversation;
      } | null)
    | ({
        relationTo: 'pattern-reports';
        value: number | PatternReport;
      } | null)
    | ({
        relationTo: 'episodes';
        value: number | Episode;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'art-historical-references';
        value: number | ArtHistoricalReference;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'image-capture-technologies';
        value: number | ImageCaptureTechnology;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'triptychs';
        value: number | Triptych;
      } | null)
    | ({
        relationTo: 'small-prints';
        value: number | SmallPrint;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  nameLegal?: T;
  generateSlug?: T;
  slug?: T;
  careerStage?: T;
  primaryActorType?: T;
  actorRoles?: T;
  platformJoinDate?: T;
  externalIdentifiers?:
    | T
    | {
        type?: T;
        value?: T;
        verified?: T;
        id?: T;
      };
  ulanUri?: T;
  wikidataUri?: T;
  bioFull?: T;
  bioMedium?: T;
  bioShort?: T;
  statementFull?: T;
  statementMedium?: T;
  statementShort?: T;
  practiceNote?: T;
  creditLine?: T;
  locations?:
    | T
    | {
        city?: T;
        country?: T;
        type?: T;
        primary?: T;
        current?: T;
        startYear?: T;
        id?: T;
      };
  publicEmail?: T;
  website?: T;
  instagramUrl?: T;
  otherLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        subject?: T;
        yearStart?: T;
        yearEnd?: T;
        city?: T;
        country?: T;
        cvVisible?: T;
        id?: T;
      };
  selectedCollections?:
    | T
    | {
        institutionName?: T;
        city?: T;
        country?: T;
        acquisitionYear?: T;
        cvVisible?: T;
        sourceOfTruth?: T;
        linkedArtworkId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-knowledge_select".
 */
export interface PracticeKnowledgeSelect<T extends boolean = true> {
  slug?: T;
  sectionLabel?: T;
  content?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  yearStart?: T;
  yearEnd?: T;
  city?: T;
  country?: T;
  coverImage?: T;
  status?: T;
  jsonldOutput?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lines_select".
 */
export interface LinesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  recordOrigin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-conversations_select".
 */
export interface StudioConversationsSelect<T extends boolean = true> {
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        timestamp?: T;
        id?: T;
      };
  summary?: T;
  summaryEmbedding?: T;
  lines?: T;
  relatedArtwork?: T;
  relatedEpisode?: T;
  recordOrigin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pattern-reports_select".
 */
export interface PatternReportsSelect<T extends boolean = true> {
  weekStart?: T;
  patterns?:
    | T
    | {
        kind?: T;
        label?: T;
        sampleFieldNoteIDs?:
          | T
          | {
              id?: T;
            };
        sampleArtworks?: T;
        score?: T;
        id?: T;
      };
  digestSummary?: T;
  recordOrigin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  title?: T;
  series?: T;
  status?: T;
  concept?: T;
  shotList?: T;
  storyboard?:
    | T
    | {
        name?: T;
        mediaType?: T;
        notes?: T;
        id?: T;
      };
  assembly?:
    | T
    | {
        beatName?: T;
        clipFieldNoteId?: T;
        notes?: T;
        id?: T;
      };
  captionDrafts?:
    | T
    | {
        text?: T;
        channel?: T;
        id?: T;
      };
  lines?: T;
  clipFieldNoteIds?:
    | T
    | {
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  aatUri?: T;
  iconclassNotation?: T;
  lcshUri?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "art-historical-references_select".
 */
export interface ArtHistoricalReferencesSelect<T extends boolean = true> {
  artworkTitle?: T;
  artistName?: T;
  yearCreated?: T;
  medium?: T;
  institution?: T;
  imageUrl?: T;
  referenceUrl?: T;
  wikidataUri?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventId?: T;
  eventType?: T;
  eventTypeCustom?: T;
  status?: T;
  featured?: T;
  startDate?: T;
  endDate?: T;
  isOngoing?: T;
  openingDate?: T;
  yearStart?: T;
  venueName?: T;
  venueCity?: T;
  venueCountry?: T;
  venueTgnUri?: T;
  venueUrl?: T;
  venueWikidataUri?: T;
  isOnline?: T;
  onlineEventUrl?: T;
  additionalVenues?:
    | T
    | {
        venueName?: T;
        venueCity?: T;
        venueCountry?: T;
        startDate?: T;
        endDate?: T;
        venueUrl?: T;
        id?: T;
      };
  artworks?: T;
  artworkPresentationNote?: T;
  organiser?: T;
  curator?: T;
  role?: T;
  coExhibitors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  catalogue?: T;
  catalogueUrl?: T;
  pressUrl?: T;
  recordingUrl?: T;
  descriptionShort?: T;
  descriptionLong?: T;
  artistNote?: T;
  pressQuote?: T;
  publicationTitle?: T;
  publicationAuthor?: T;
  bibliographyAuthor?: T;
  publicationIssn?: T;
  publicationIsbn?: T;
  publicationPages?: T;
  publicationUrl?: T;
  awardGrantingOrganisation?: T;
  awardAmount?: T;
  awardAmountCurrency?: T;
  awardOutcome?: T;
  residencyOrganisation?: T;
  residencyType?: T;
  residencyWorksProduced?: T;
  institution?: T;
  degree?: T;
  subject?: T;
  cvVisible?: T;
  commissionClient?: T;
  commissionSite?: T;
  commissionBudget?: T;
  cvSection?: T;
  cvDisplayTitle?: T;
  cvPriority?: T;
  excludeFromCv?: T;
  jsonldSameAs?:
    | T
    | {
        uri?: T;
        id?: T;
      };
  jsonldPreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-capture-technologies_select".
 */
export interface ImageCaptureTechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  approximatePeriodStart?: T;
  approximatePeriodEnd?: T;
  exampleImage?: T;
  exampleImageCredit?: T;
  wikidataUri?: T;
  wikipediaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  primaryImage?: T;
  primaryMediaType?: T;
  primaryImageAltText?: T;
  posterImage?: T;
  posterImageAltText?: T;
  wpImageUrl?: T;
  title?: T;
  altTitle?: T;
  slug?: T;
  creator?: T;
  series?: T;
  seriesSlug?: T;
  status?: T;
  recordOrigin?: T;
  yearCreated?: T;
  yearCompleted?: T;
  yearStart?: T;
  datePublished?: T;
  wp_id?: T;
  oldWpUrl?: T;
  medium?: T;
  mediumOther?: T;
  measurementType?: T;
  support?: T;
  framing?: T;
  weight?: T;
  dimensionUnit?: T;
  widthWhole?: T;
  widthFraction?: T;
  heightWhole?: T;
  heightFraction?: T;
  depthWhole?: T;
  depthFraction?: T;
  widthMm?: T;
  heightMm?: T;
  depthMm?: T;
  dimensionsDisplay?: T;
  aspectRatio?: T;
  widthPx?: T;
  heightPx?: T;
  resolutionDpi?: T;
  fileFormat?: T;
  fileSize?: T;
  colorSpace?: T;
  duration?: T;
  durationSeconds?: T;
  looped?: T;
  soundDesign?: T;
  condition?: T;
  conditionNotes?: T;
  workState?: T;
  workStateNotes?: T;
  workStateDate?: T;
  materialAndProcessMeaning?: T;
  stateVersions?: T;
  sizeTier?: T;
  orientation?: T;
  city?: T;
  country?: T;
  cityTgnUri?: T;
  movementTags?: T;
  styleTags?: T;
  subjectTags?: T;
  genreTags?: T;
  periodTags?: T;
  conceptualKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  events?: T;
  artHistoricalReferences?: T;
  artHistoricalContext?: T;
  seriesContext?: T;
  consciousRejections?: T;
  formalContributionAssessment?: T;
  descriptionShort?: T;
  descriptionLong?: T;
  description?: T;
  intent?: T;
  intentVsOutcome?: T;
  makingNote?: T;
  directInspiration?: T;
  encounterNote?: T;
  workContext?: T;
  processNotes?: T;
  sourceMaterials?: T;
  aiDescription?: T;
  aiVibe?: T;
  dominantColors?:
    | T
    | {
        hex?: T;
        id?: T;
      };
  paintedFieldColors?:
    | T
    | {
        hex?: T;
        id?: T;
      };
  compositionalNotes?: T;
  analysisModelVersion?: T;
  recognitionTimeline?: T;
  clipEmbedding?: T;
  embedding?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  genre?: T;
  alternateViewImages?:
    | T
    | {
        image?: T;
        caption?: T;
        altText?: T;
        aspectRatio?: T;
        id?: T;
      };
  detailImages?:
    | T
    | {
        image?: T;
        caption?: T;
        altText?: T;
        aspectRatio?: T;
        id?: T;
      };
  installationShots?:
    | T
    | {
        image?: T;
        venue?: T;
        date?: T;
        altText?: T;
        aspectRatio?: T;
        id?: T;
      };
  documentationImages?:
    | T
    | {
        image?: T;
        caption?: T;
        altText?: T;
        aspectRatio?: T;
        documentationRole?: T;
        id?: T;
      };
  arTargetImage?: T;
  videoFile?: T;
  videoUrl?: T;
  videoCaption?: T;
  documentationVideoUrl?: T;
  documentationVideoFile?: T;
  videos?:
    | T
    | {
        videoType?: T;
        videoFile?: T;
        videoUrl?: T;
        posterImage?: T;
        title?: T;
        description?: T;
        videoRole?: T;
        id?: T;
      };
  additionalImages?:
    | T
    | {
        image?: T;
        caption?: T;
        imageRole?: T;
        id?: T;
      };
  arEnabled?: T;
  arWidthM?: T;
  arHeightM?: T;
  arDepthM?: T;
  arModelUrl?: T;
  arModelGlbUrl?: T;
  arAllowScaling?: T;
  arLastGenerated?: T;
  locationCreated?:
    | T
    | {
        label?: T;
        city?: T;
        country?: T;
        countryCode?: T;
        lat?: T;
        lng?: T;
      };
  artworkHolder?:
    | T
    | {
        holderType?: T;
        holderName?: T;
        holderUrl?: T;
      };
  provenanceNotes?: T;
  currentLocation?:
    | T
    | {
        category?: T;
        locationDetail?: T;
      };
  ownershipHistory?: T;
  provenanceOriginKnown?: T;
  loanHistory?: T;
  provenanceConfidenceLayer?: T;
  exhibitionHistory?:
    | T
    | {
        event?: T;
        workIncluded?: T;
        notes?: T;
        id?: T;
      };
  availabilityStatus?: T;
  consignmentDetails?: T;
  listingCurrency?: T;
  askingPrice?: T;
  originalAskingPrice?: T;
  priceNotes?: T;
  insuranceValue?: T;
  insuranceValueDate?: T;
  galleryReference?: T;
  galleryText?: T;
  salesRecord?: T;
  totalRevenue?: T;
  editionType?: T;
  editions?:
    | T
    | {
        formatLabel?: T;
        widthCm?: T;
        heightCm?: T;
        substrate?: T;
        printTechnique?: T;
        totalEditionSize?: T;
        artistProofs?: T;
        remaining?: T;
        pricePerPrint?: T;
        currency?: T;
        certificate?: T;
        signature?: T;
        notes?: T;
        id?: T;
      };
  editionNotes?: T;
  isForSale?: T;
  offers?:
    | T
    | {
        price?: T;
        priceCurrency?: T;
        availability?: T;
        inquiryUrl?: T;
      };
  printEditions?:
    | T
    | {
        editionSize?: T;
        format?: T;
        substrate?: T;
        price?: T;
        priceCurrency?: T;
        availability?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  sameAs?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  license?: T;
  creditText?: T;
  sameAsUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  jsonldPreview?: T;
  jsonldWidthPreview?: T;
  jsonldHeightPreview?: T;
  jsonldCreatorPreview?: T;
  mop_sourcePhotographDetails?: T;
  mop_imageCaptureType?: T;
  mop_historicalContext?: T;
  mop_triptychPosition?: T;
  mop_triptychGroupNote?: T;
  mop_arVideoUrl?: T;
  mop_arRapScript?: T;
  mop_lat?: T;
  mop_lng?: T;
  ach?:
    | T
    | {
        mapAndTour?:
          | T
          | {
              mapPresence?: T;
              lat?: T;
              lng?: T;
              cityPlaceholderColor?: T;
              tourSequence?: T;
              grandTour?: T;
              grandTourSequence?: T;
              tourStopCopy?: T;
            };
        overlay?:
          | T
          | {
              overlayColors?:
                | T
                | {
                    hex?: T;
                    id?: T;
                  };
              overlayRects?:
                | T
                | {
                    color?: T;
                    x?: T;
                    y?: T;
                    w?: T;
                    h?: T;
                    id?: T;
                  };
            };
        sourcePhotograph?:
          | T
          | {
              sourceImage?: T;
              sourceImageAltText?: T;
              sourceTitle?: T;
              sourceCreator?: T;
              sourceCreatorWikidataUri?: T;
              approximateDate?: T;
              approximateDateYear?: T;
              imageCaptureType?: T;
              sourceWikidataUri?: T;
              sourceWikimediaCommonsUrl?: T;
              sourceInstitution?: T;
              sourceInstitutionWikidataUri?: T;
              sourceInstitutionUrl?: T;
              sourceLicense?: T;
              sourceLicenseUrl?: T;
              sourceCredit?: T;
            };
        location?:
          | T
          | {
              locationWikidataUri?: T;
              locationTGNUri?: T;
              wikipediaUrl?: T;
              wikipediaExcerpt?: T;
              keyHistoricalDates?:
                | T
                | {
                    year?: T;
                    event?: T;
                    id?: T;
                  };
              conceptCopy?: T;
              fieldRecordingUrl?: T;
              fieldRecordingCredit?: T;
            };
        revealSlider?:
          | T
          | {
              transferImage?: T;
              sliderAxis?: T;
            };
        ar?:
          | T
          | {
              arEnabled?: T;
              arMarkerFile?: T;
              arMarkerStatus?: T;
              arButtonColors?:
                | T
                | {
                    hex?: T;
                    id?: T;
                  };
              arVideos?:
                | T
                | {
                    type?: T;
                    videoUrl?: T;
                    posterImage?: T;
                    duration?: T;
                    captions?: T;
                    id?: T;
                  };
              historyTranscript?: T;
              freestyleTranscript?: T;
            };
        mop?:
          | T
          | {
              imageCaptureType?: T;
              imageCaptureLabel?: T;
              triptychPosition?: T;
              availabilityStatus?: T;
              relatedTriptychs?: T;
            };
      };
  dcs_photoTitle?: T;
  dcs_cityData?:
    | T
    | {
        population?: T;
        area?: T;
        density?: T;
        elevation?: T;
      };
  dcs_videos?:
    | T
    | {
        videoType?: T;
        videoFile?: T;
        videoUrl?: T;
        posterImage?: T;
        title?: T;
        videoRole?: T;
        id?: T;
      };
  mc_cityData?:
    | T
    | {
        population?: T;
        area?: T;
        density?: T;
        elevation?: T;
      };
  mc_videos?:
    | T
    | {
        videoType?: T;
        videoFile?: T;
        videoUrl?: T;
        posterImage?: T;
        title?: T;
        videoRole?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "triptychs_select".
 */
export interface TriptychsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  series?: T;
  status?: T;
  yearStart?: T;
  yearCompleted?: T;
  city?: T;
  country?: T;
  panels?:
    | T
    | {
        artwork?: T;
        position?: T;
        id?: T;
      };
  description?: T;
  descriptionShort?: T;
  descriptionLong?: T;
  intent?: T;
  conceptualKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  artHistoricalReferences?: T;
  artHistoricalContext?: T;
  seriesContext?: T;
  formalContributionAssessment?: T;
  vendureProductId?: T;
  printSets?:
    | T
    | {
        size?: T;
        edition?: T;
        vendureProductId?: T;
        printAvailableCount?: T;
        id?: T;
      };
  printEditionReleaseDate?: T;
  signedAndNumbered?: T;
  originalsSoldDate?: T;
  originalsBuyer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "small-prints_select".
 */
export interface SmallPrintsSelect<T extends boolean = true> {
  artwork?: T;
  available?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  sessionId?: T;
  sessionType?: T;
  status?: T;
  artistId?: T;
  artworkRecord?: T;
  triptychRecord?: T;
  completedAt?: T;
  messages?: T;
  preUploadStep?: T;
  firstImpression?: T;
  secondDescription?: T;
  highlightedMediaSlot?: T;
  stagedMedia?: T;
  fieldUpdateTimeline?: T;
  agentDraftDescriptionShort?: T;
  agentDraftDescriptionLong?: T;
  agentDraftConceptualKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  agentDraftFormalContributionAssessment?: T;
  sessionNotes?: T;
  weakPhases?: T;
  blindDescriptionUseful?: T;
  formalContributionAccuracy?: T;
  dialogueRefinementFlag?: T;
  refinementNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Print set builder: Vendure product, pack size, and frame display labels. Not per SmallPrint row.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-set-config".
 */
export interface PrintSetConfig {
  id: number;
  /**
   * Single Vendure product ID for the full print set (fixed price).
   */
  vendureProductId: string;
  /**
   * Number of prints the customer selects per order.
   */
  packSize: number;
  /**
   * Display name of the frame format (e.g. current product name on the site).
   */
  frameLabel?: string | null;
  /**
   * Public-facing notes about the frame / border treatment at fulfilment.
   */
  frameNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * When off, the set builder is hidden on the storefront.
   */
  active?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-set-config_select".
 */
export interface PrintSetConfigSelect<T extends boolean = true> {
  vendureProductId?: T;
  packSize?: T;
  frameLabel?: T;
  frameNotes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}